[phases.setup]
nixPkgs = ["php84", "php84Packages.composer"]

[phases.build]
cmds = ["composer install --no-interaction --prefer-dist --optimize-autoloader"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"